-- Seed DE + FR translations for taxonomy_nodes
-- Idempotent via ON CONFLICT
BEGIN;

INSERT INTO taxonomy_translations (node_slug, locale, label) VALUES
-- Fashion
('fashion','de','Mode'),
('fashion','fr','Mode'),
('fashion-women','de','Damen'),
('fashion-women','fr','Femmes'),
('fashion-women-clothing','de','Bekleidung'),
('fashion-women-clothing','fr','Vêtements'),
('fashion-women-dresses','de','Kleider'),
('fashion-women-dresses','fr','Robes'),
('fashion-women-outerwear','de','Oberbekleidung'),
('fashion-women-outerwear','fr','Vêtements d''extérieur'),
('fashion-women-pants','de','Hosen'),
('fashion-women-pants','fr','Pantalons'),
('fashion-women-tops','de','Oberteile'),
('fashion-women-tops','fr','Hauts'),
('fashion-men','de','Herren'),
('fashion-men','fr','Hommes'),
('fashion-men-clothing-basic','de','Basis-Bekleidung'),
('fashion-men-clothing-basic','fr','Vêtements basiques'),
('fashion-men-coats','de','Mäntel & Jacken'),
('fashion-men-coats','fr','Manteaux & vestes'),
('fashion-men-hoodies','de','Hoodies & Sweatshirts'),
('fashion-men-hoodies','fr','Sweats à capuche'),
('fashion-men-jeans','de','Jeans'),
('fashion-men-jeans','fr','Jeans'),
('fashion-men-pants','de','Hosen'),
('fashion-men-pants','fr','Pantalons'),
('fashion-men-polo','de','Poloshirts'),
('fashion-men-polo','fr','Polos'),
('fashion-men-shirts','de','Hemden'),
('fashion-men-shirts','fr','Chemises'),
('fashion-men-shorts','de','Shorts'),
('fashion-men-shorts','fr','Shorts'),
('fashion-men-tshirts','de','T-Shirts'),
('fashion-men-tshirts','fr','T-shirts'),
('fashion-men-underwear','de','Unterwäsche'),
('fashion-men-underwear','fr','Sous-vêtements'),
('fashion-shoes','de','Schuhe'),
('fashion-shoes','fr','Chaussures'),
('fashion-shoes-women','de','Damenschuhe'),
('fashion-shoes-women','fr','Chaussures femme'),
('fashion-shoes-men','de','Herrenschuhe'),
('fashion-shoes-men','fr','Chaussures homme'),
('fashion-shoes-kids','de','Kinderschuhe'),
('fashion-shoes-kids','fr','Chaussures enfant'),
('fashion-shoes-accessories','de','Schuhzubehör'),
('fashion-shoes-accessories','fr','Accessoires chaussures'),
('fashion-underwear','de','Unterwäsche & Dessous'),
('fashion-underwear','fr','Sous-vêtements & lingerie'),
('fashion-underwear-women','de','Damen-Dessous'),
('fashion-underwear-women','fr','Lingerie femme'),
('fashion-underwear-men','de','Herren-Unterwäsche'),
('fashion-underwear-men','fr','Sous-vêtements homme'),
('fashion-underwear-socks','de','Socken & Strumpfwaren'),
('fashion-underwear-socks','fr','Chaussettes & collants'),
('fashion-accessories','de','Accessoires'),
('fashion-accessories','fr','Accessoires'),
('fashion-accessories-bags','de','Taschen & Geldbörsen'),
('fashion-accessories-bags','fr','Sacs & portefeuilles'),
('fashion-accessories-hats','de','Hüte & Kappen'),
('fashion-accessories-hats','fr','Chapeaux & casquettes'),
('fashion-accessories-jewelry','de','Schmuck'),
('fashion-accessories-jewelry','fr','Bijoux'),
('fashion-accessories-watches','de','Uhren'),
('fashion-accessories-watches','fr','Montres'),
-- Beauty
('beauty','de','Beauty'),
('beauty','fr','Beauté'),
('beauty-makeup','de','Make-up'),
('beauty-makeup','fr','Maquillage'),
('beauty-makeup-face','de','Gesichts-Make-up'),
('beauty-makeup-face','fr','Maquillage visage'),
('beauty-makeup-eyes','de','Augen-Make-up'),
('beauty-makeup-eyes','fr','Maquillage yeux'),
('beauty-makeup-lips','de','Lippen-Make-up'),
('beauty-makeup-lips','fr','Maquillage lèvres'),
('beauty-makeup-nails','de','Nagelpflege'),
('beauty-makeup-nails','fr','Soin des ongles'),
('beauty-skincare','de','Hautpflege'),
('beauty-skincare','fr','Soins de la peau'),
('beauty-skincare-face','de','Gesichtspflege'),
('beauty-skincare-face','fr','Soins du visage'),
('beauty-skincare-body','de','Körperpflege'),
('beauty-skincare-body','fr','Soins du corps'),
('beauty-skincare-sun','de','Sonnenpflege'),
('beauty-skincare-sun','fr','Protection solaire'),
('beauty-haircare','de','Haarpflege'),
('beauty-haircare','fr','Soins capillaires'),
('beauty-hair-styling','de','Styling'),
('beauty-hair-styling','fr','Coiffure'),
('beauty-hair-extensions','de','Extensions & Perücken'),
('beauty-hair-extensions','fr','Extensions & perruques'),
('beauty-fragrance','de','Düfte'),
('beauty-fragrance','fr','Parfums'),
-- Electronics
('electronics','de','Elektronik'),
('electronics','fr','Électronique'),
('electronics-phones','de','Handys & Zubehör'),
('electronics-phones','fr','Téléphones & accessoires'),
('electronics-phones-cases','de','Hüllen & Cover'),
('electronics-phones-cases','fr','Coques & étuis'),
('electronics-phones-chargers','de','Ladegeräte & Kabel'),
('electronics-phones-chargers','fr','Chargeurs & câbles'),
('electronics-phones-sim','de','SIM-Karten & Adapter'),
('electronics-phones-sim','fr','Cartes SIM & adaptateurs'),
('electronics-audio','de','Audio'),
('electronics-audio','fr','Audio'),
('electronics-audio-headphones','de','Kopfhörer & Ohrhörer'),
('electronics-audio-headphones','fr','Casques & écouteurs'),
('electronics-audio-speakers','de','Lautsprecher'),
('electronics-audio-speakers','fr','Enceintes'),
('electronics-computing','de','Computer & Tablets'),
('electronics-computing','fr','Ordinateurs & tablettes'),
('electronics-cameras','de','Kameras'),
('electronics-cameras','fr','Appareils photo'),
('electronics-gaming','de','Gaming'),
('electronics-gaming','fr','Gaming'),
('electronics-wearables','de','Smartwatches & Wearables'),
('electronics-wearables','fr','Montres connectées & wearables'),
-- Home
('home','de','Zuhause'),
('home','fr','Maison'),
('home-decor','de','Deko'),
('home-decor','fr','Décoration'),
('home-furniture','de','Möbel'),
('home-furniture','fr','Meubles'),
('home-kitchen','de','Küche & Esszimmer'),
('home-kitchen','fr','Cuisine & salle à manger'),
('home-storage','de','Aufbewahrung'),
('home-storage','fr','Rangement'),
('home-textiles','de','Bettwäsche & Heimtextilien'),
('home-textiles','fr','Linge de lit & textile'),
('home-appliances','de','Haushaltsgeräte'),
('home-appliances','fr','Électroménager'),
('home-appliances-kitchen','de','Küchengeräte'),
('home-appliances-kitchen','fr','Petit électroménager cuisine'),
('home-appliances-cleaning','de','Reinigungsgeräte'),
('home-appliances-cleaning','fr','Appareils de nettoyage'),
('home-appliances-personal-care','de','Körperpflegegeräte'),
('home-appliances-personal-care','fr','Appareils de soins personnels'),
-- Health
('health','de','Gesundheit & Wellness'),
('health','fr','Santé & bien-être'),
('health-personal','de','Körperpflege'),
('health-personal','fr','Soins personnels'),
('health-supplements','de','Nahrungsergänzung'),
('health-supplements','fr','Compléments alimentaires'),
-- Toys
('toys','de','Spielzeug & Kinder'),
('toys','fr','Jouets & enfants'),
('toys-games','de','Spielzeug & Spiele'),
('toys-games','fr','Jouets & jeux'),
('toys-baby','de','Baby-Ausstattung'),
('toys-baby','fr','Articles bébé'),
('toys-school','de','Schulbedarf'),
('toys-school','fr','Fournitures scolaires'),
-- Sports
('sports','de','Sport & Outdoor'),
('sports','fr','Sport & plein air'),
('sports-fitness','de','Fitness'),
('sports-fitness','fr','Fitness'),
('sports-outdoor','de','Outdoor & Camping'),
('sports-outdoor','fr','Plein air & camping'),
('sports-cycling','de','Radsport'),
('sports-cycling','fr','Cyclisme'),
-- Auto / Tools / Office / Pets / Garden / Food / Other
('automotive','de','Auto & Motorrad'),
('automotive','fr','Auto & moto'),
('auto-parts','de','Teile'),
('auto-parts','fr','Pièces'),
('auto-accessories','de','Zubehör'),
('auto-accessories','fr','Accessoires'),
('tools','de','Werkzeug & Heimwerken'),
('tools','fr','Outils & bricolage'),
('tools-hand','de','Handwerkzeug'),
('tools-hand','fr','Outils à main'),
('tools-power','de','Elektrowerkzeug'),
('tools-power','fr','Outils électriques'),
('office','de','Büro'),
('office','fr','Bureau'),
('office-supplies','de','Bürobedarf'),
('office-supplies','fr','Fournitures de bureau'),
('pets','de','Haustiere'),
('pets','fr','Animaux'),
('pets-supplies','de','Haustierzubehör'),
('pets-supplies','fr','Accessoires animaux'),
('garden','de','Garten & Außenbereich'),
('garden','fr','Jardin & extérieur'),
('food','de','Lebensmittel & Getränke'),
('food','fr','Alimentation & boissons'),
('other','de','Sonstiges'),
('other','fr','Autre')
ON CONFLICT (node_slug, locale) DO UPDATE SET label = EXCLUDED.label;

COMMIT;
