/**
 * Sitemap INDEX — references all sub-sitemaps so Google can discover them.
 * Replaces the auto-generated app/sitemap.ts.
 *
 * Sub-sitemaps:
 *   /static-sitemap.xml         — static pages, categories, SEO landings
 *   /products/sitemap/N.xml     — product chunks (10k each), generated by app/products/sitemap.ts
 *   /videos/sitemap.xml         — public videos, generated by app/videos/sitemap.ts
 */

import { dbQuery } from "@/lib/db";
import { NextResponse } from "next/server";

export const dynamic = "force-dynamic";
export const revalidate = 3600;

const BASE_URL = process.env.NEXT_PUBLIC_APP_URL ?? "https://swypik.com";
const CHUNK_SIZE = 10000;

async function countSafeProducts(): Promise<number> {
  try {
    const { rows } = await dbQuery<{ n: string }>(
      `SELECT count(*)::text AS n FROM marketplace_products p
       WHERE p.status='active' AND p.effective_label='safe'`,
    );
    return Number(rows[0]?.n || 0);
  } catch {
    return 0;
  }
}

export async function GET() {
  const now = new Date().toISOString();
  const productTotal = await countSafeProducts();
  const productChunks = Math.max(1, Math.ceil(productTotal / CHUNK_SIZE));

  const entries: string[] = [];
  entries.push(`  <sitemap><loc>${BASE_URL}/static-sitemap.xml</loc><lastmod>${now}</lastmod></sitemap>`);
  for (let i = 0; i < productChunks; i++) {
    entries.push(`  <sitemap><loc>${BASE_URL}/products/sitemap/${i}.xml</loc><lastmod>${now}</lastmod></sitemap>`);
  }
  entries.push(`  <sitemap><loc>${BASE_URL}/videos/sitemap.xml</loc><lastmod>${now}</lastmod></sitemap>`);
  entries.push(`  <sitemap><loc>${BASE_URL}/blog/sitemap.xml</loc><lastmod>${now}</lastmod></sitemap>`);

  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${entries.join("\n")}
</sitemapindex>
`;

  return new NextResponse(xml, {
    status: 200,
    headers: {
      "Content-Type": "application/xml; charset=utf-8",
      "Cache-Control": "public, s-maxage=3600, stale-while-revalidate=86400",
    },
  });
}
