export const THEME = {
  name: "ChatGPT Clean",
  colors: {
    bg: "#FFFFFF",
    bgSoft: "#F7F7F8",
    card: "#F7F7F8",
    cardHover: "#ECECF1",
    text: "#0D0D0D",
    muted: "#6E6E80",
    border: "#E5E5E5",
    borderLight: "#ECECF1",
    primary: "#0D0D0D",
    primaryDark: "#0E8F6F",
    accent: "#0D0D0D",
    cart: "#0D0D0D",
    cartDark: "#0E8F6F",
    discount: "#DC2626",
    premium: "#8E44AD",
    trust: "#2563EB",
    warning: "#B45309",
    gold: "#FACC15",
  },
  classes: {
    appBg: "bg-white text-[#0D0D0D]",
    pageBg: "bg-white",
    card: "bg-[#F7F7F8] border border-[#E5E5E5] rounded-2xl",
    cardHover: "hover:bg-[#ECECF1] hover:border-[#D1D1D6] transition-all duration-200",
    heroCard: "bg-[#F7F7F8] border border-[#E5E5E5] rounded-2xl",
    primaryButton: "bg-[#0D0D0D] text-white hover:bg-[#0E8F6F] active:scale-[0.98] transition-all",
    cartButton: "bg-[#0D0D0D] text-white hover:bg-[#2D2D2D] active:scale-[0.98] transition-all",
    discountBadge: "bg-[#DC2626] text-white",
    premiumBadge: "bg-[#8E44AD] text-white",
    trustBadge: "bg-[#2563EB] text-white",
    softInput: "bg-[#F7F7F8] border border-[#E5E5E5] focus-within:border-[#0D0D0D] focus-within:shadow-[0_0_0_1px_#0D0D0D] transition-all",
    glass: "bg-white/95 backdrop-blur-xl border-t border-[#E5E5E5]",
    glassNav: "bg-white/95 backdrop-blur-xl border-t border-[#E5E5E5]",
  },
};

// Romanian category translations
export const CATEGORY_RO: Record<string, string> = {
  "Women's Clothing": "Îmbrăcăminte Femei",
  "Men's Clothing": "Îmbrăcăminte Bărbați",
  "Home, Garden & Furniture": "Casă & Grădină",
  "Jewelry & Watches": "Bijuterii & Ceasuri",
  "Bags & Shoes": "Genți & Încălțăminte",
  "Pet Supplies": "Animale de Companie",
  "Health, Beauty & Hair": "Frumusețe & Sănătate",
  "Toys, Kids & Babies": "Copii & Bebeluși",
  "Sports & Outdoors": "Sport & Outdoor",
  "Automobiles & Motorcycles": "Auto & Moto",
  "Home Improvement": "Bricolaj & Scule",
  "Consumer Electronics": "Electronice",
  "Phones & Accessories": "Telefoane & Accesorii",
  "Computer & Office": "Calculatoare & Birou",
  // Mid-level
  "Tops & Sets": "Topuri & Seturi",
  "Outerwear & Jackets": "Jachete & Paltoane",
  "Bottoms": "Pantaloni & Fuste",
  "Accessories": "Accesorii",
  "Weddings & Events": "Nunți & Evenimente",
  "Couple&Parent-Child Clothing": "Cupluri & Familie",
  "Home Storage": "Depozitare",
  "Fashion Jewelry": "Bijuterii Fashion",
  "Fine Jewelry": "Bijuterii Fine",
  "T-Shirts": "Tricouri",
  // Sub-level
  "Lady Dresses": "Rochii",
  "Blazers": "Blazere",
  "Suits & Sets": "Costume & Seturi",
  "Sweaters": "Pulovere",
  "Blouses & Shirts": "Bluze & Cămăși",
  "Wide Leg Pants": "Pantaloni Largi",
  "Women's Short-Sleeved Shirts": "Tricouri Damă",
  "Basic Jacket": "Jachete Basic",
  "Woman Jeans": "Blugi Damă",
  "Woman Hoodies & Sweatshirts": "Hanorace Damă",
  "Rompers": "Salopete",
  "Skirts": "Fuste",
  "Woman Hats & Caps": "Pălării & Șepci",
  "Woman Socks": "Șosete Damă",
  "Woman Shorts": "Pantaloni Scurți",
  "Pants & Capris": "Pantaloni & Capri",
  "Scarves & Wraps": "Eșarfe & Fulare",
  "Women's Long-Sleeved Shirts": "Cămăși ML Damă",
  "Belts & Cummerbunds": "Curele",
  "Woman Trench": "Trenciuri",
  "Jumpsuits": "Salopete",
  "Eyewear & Accessories": "Ochelari",
  "Leggings": "Colanți",
  "Wool & Blend": "Lână & Blend",
  "Woman Gloves & Mittens": "Mănuși Damă",
  "Women's Padded Jackets": "Geci Damă",
  "Furniture": "Mobilier",
  "Women's Camis": "Topuri Damă",
  "Leather & Suede": "Piele & Suede",
  "Evening Dresses": "Rochii de Seară",
  "Necklace & Pendants": "Coliere & Pandantive",
  "Earrings": "Cercei",
  "Bracelets & Bangles": "Brățări",
  "Rings": "Inele",
  "Casual Pants": "Pantaloni Casual",
  "Suits & Blazer": "Costume & Blazere",
  "Print": "Imprimate",
  "Solid": "Uni",
  "Men's Shirts": "Cămăși Bărbați",
  "925 Silver Jewelry": "Argint 925",
  "Flower Girl Dresses": "Rochii Fetițe",
  "Wedding Dresses": "Rochii Mireasă",
  "Prom Dresses": "Rochii Bal",
  "Face Masks": "Măști Faciale",
  "Men's Sweaters": "Pulovere Bărbați",
  "Man Shorts": "Pantaloni Scurți Bărbați",
  "Home Office Storage": "Depozitare Birou",
  "Women's Vests": "Veste Damă",
  "Woman Prescription Glasses": "Ochelari Damă",
  "Couple&Parent-Child Suits": "Costume Familie",
};

export function translateCategory(en: string): string {
  return CATEGORY_RO[en] || en;
}

export function commerceBadgeClass(label?: string) {
  if (!label) return "bg-[#F7F7F8] text-[#0D0D0D]";
  if (label.includes("Bundle") || label.includes("Premium")) return "bg-[#8E44AD] text-white";
  if (label.includes("sigur") || label.includes("Alegere")) return "bg-[#2563EB] text-white";
  if (label.includes("coș") || label.includes("adăugat")) return "bg-[#0D0D0D] text-white";
  if (label.includes("vinde") || label.includes("popular")) return "bg-[#DC2626] text-white";
  return "bg-[#F7F7F8] text-[#0D0D0D]";
}
