/**
 * Radiourile naționale din România cu stream-urile oficiale verificate — apar
 * primele în rândul „Radio RO” și sunt fallback-ul garantat când Radio-Browser
 * nu răspunde (și înainte de prima preîncălzire, lib/prewarm/catalogs.ts).
 */
import type { AudioItemDto } from "./types";

// Fallback verificat cu stream-urile directe oficiale ale radiourilor din România
export const CURATED_ROMANIAN_STATIONS: AudioItemDto[] = [
    {
        id: "radio_kissfm_ro",
        slug: "kiss-fm-romania",
        title: "Kiss FM",
        artist: "Radio Live România",
        coverUrl: "",
        streamUrl: "https://live.kissfm.ro/kissfm.aacp",
        durationMs: 0,
        genre: "Pop & Top 40",
        source: "radio",
        isLive: true,
        stationCountry: "România",
        stationVotes: 9500,
    },
    {
        id: "radio_zu_ro",
        slug: "radio-zu",
        title: "Radio ZU",
        artist: "Radio Live România",
        coverUrl: "",
        streamUrl: "https://stream.radiozu.ro:8020/live.aac",
        durationMs: 0,
        genre: "Pop & Hituri",
        source: "radio",
        isLive: true,
        stationCountry: "România",
        stationVotes: 9200,
    },
    {
        id: "radio_europafm_ro",
        slug: "europa-fm-romania",
        title: "Europa FM",
        artist: "Radio Live România",
        coverUrl: "",
        streamUrl: "https://astreaming.europafm.ro:8000/EuropaFM_aac",
        durationMs: 0,
        genre: "Știri & Pop",
        source: "radio",
        isLive: true,
        stationCountry: "România",
        stationVotes: 8700,
    },
    {
        id: "radio_rockfm_ro",
        slug: "rock-fm-romania",
        title: "Rock FM",
        artist: "Radio Live România",
        coverUrl: "",
        streamUrl: "https://live.rockfm.ro/rockfm.aacp",
        durationMs: 0,
        genre: "Rock Clasic & Modern",
        source: "radio",
        isLive: true,
        stationCountry: "România",
        stationVotes: 8900,
    },
    {
        id: "radio_magicfm_ro",
        slug: "magic-fm-romania",
        title: "Magic FM",
        artist: "Radio Live România",
        coverUrl: "",
        streamUrl: "https://live.magicfm.ro/magicfm.aacp",
        durationMs: 0,
        genre: "Soft Rock & Clasic",
        source: "radio",
        isLive: true,
        stationCountry: "România",
        stationVotes: 7800,
    },
    {
        id: "radio_digifm_ro",
        slug: "digi-fm-romania",
        title: "Digi FM",
        artist: "Radio Live România",
        coverUrl: "",
        streamUrl: "https://edge126.rdsnet.ro:8443/digifm/digifm.mp3",
        durationMs: 0,
        genre: "Știri & Hituri",
        source: "radio",
        isLive: true,
        stationCountry: "România",
        stationVotes: 7600,
    },
    {
        id: "radio_virgin_ro",
        slug: "virgin-radio-romania",
        title: "Virgin Radio",
        artist: "Radio Live România",
        coverUrl: "",
        streamUrl: "https://astreaming.virginradio.ro:8000/virgin_aacp",
        durationMs: 0,
        genre: "Hip-Hop & Urban",
        source: "radio",
        isLive: true,
        stationCountry: "România",
        stationVotes: 7400,
    },
    {
        id: "radio_profm_ro",
        slug: "pro-fm-romania",
        title: "PRO FM",
        artist: "Radio Live România",
        coverUrl: "",
        streamUrl: "https://edge126.rdsnet.ro:8443/profm/profm.mp3",
        durationMs: 0,
        genre: "Dance & Club",
        source: "radio",
        isLive: true,
        stationCountry: "România",
        stationVotes: 7100,
    },
    {
        id: "radio_guerrilla_ro",
        slug: "radio-guerrilla",
        title: "Radio Guerrilla",
        artist: "Radio Live România",
        coverUrl: "",
        streamUrl: "https://stream.eliberadio.ro:8000/guerrilla.aac",
        durationMs: 0,
        genre: "Alternative & Indie",
        source: "radio",
        isLive: true,
        stationCountry: "România",
        stationVotes: 6900,
    },
    {
        id: "radio_dancefm_ro",
        slug: "dance-fm-romania",
        title: "Dance FM",
        artist: "Radio Live România",
        coverUrl: "",
        streamUrl: "https://edge126.rdsnet.ro:8443/dancefm/dancefm.mp3",
        durationMs: 0,
        genre: "Electronic & House",
        source: "radio",
        isLive: true,
        stationCountry: "România",
        stationVotes: 6800,
    },
];
