/**
 * Creator badges — computed from verified status + GMV generated by clips.
 *
 * GMV = SUM(commissions.gross_amount_cents) for statuses that represent real
 * sales (approved / payable / paid). Levels:
 *   bronze  ≥ 100 €   (10_000 cents)
 *   silver  ≥ 1 000 € (100_000 cents)
 *   gold    ≥ 10 000 € (1_000_000 cents)
 *   top_seller ≥ 25 000 € (2_500_000 cents)
 */
import { dbQuery } from "@/lib/db";

export type CreatorLevel = "none" | "bronze" | "silver" | "gold";

export type CreatorBadges = {
    verified: boolean;
    level: CreatorLevel;
    topSeller: boolean;
    gmvCents: number;
};

export const BADGE_THRESHOLDS_CENTS = {
    bronze: 10_000,
    silver: 100_000,
    gold: 1_000_000,
    topSeller: 2_500_000,
} as const;

type BadgeQuery = <T = Record<string, unknown>>(
    text: string,
    params?: unknown[]
) => Promise<{ rows: T[]; rowCount: number }>;

export function levelFromGmv(gmvCents: number): CreatorLevel {
    if (gmvCents >= BADGE_THRESHOLDS_CENTS.gold) return "gold";
    if (gmvCents >= BADGE_THRESHOLDS_CENTS.silver) return "silver";
    if (gmvCents >= BADGE_THRESHOLDS_CENTS.bronze) return "bronze";
    return "none";
}

export async function getCreatorBadges(
    userId: string,
    options: { verified?: boolean; query?: BadgeQuery } = {}
): Promise<CreatorBadges> {
    const query: BadgeQuery = options.query || (dbQuery as BadgeQuery);

    const { rows } = await query<{ gmv_cents: string | number | null }>(
        `SELECT COALESCE(SUM(gross_amount_cents), 0) AS gmv_cents
       FROM commissions
      WHERE creator_id = $1
        AND status IN ('approved', 'payable', 'paid')`,
        [userId]
    );

    const gmvCents = Math.max(0, Math.trunc(Number(rows[0]?.gmv_cents ?? 0)) || 0);

    return {
        verified: Boolean(options.verified),
        level: levelFromGmv(gmvCents),
        topSeller: gmvCents >= BADGE_THRESHOLDS_CENTS.topSeller,
        gmvCents,
    };
}
