#!/bin/bash
# Audit functional: date reale in DB (read-only)
PSQL="docker exec swypik-prod-postgres-1 psql -U swypik -d swypik_prod -tAc"
echo "=== tabele video ==="
$PSQL "SELECT tablename FROM pg_tables WHERE tablename LIKE '%video%' ORDER BY 1;"
echo "=== videos pe status ==="
$PSQL "SELECT COALESCE(status,'?'), count(*) FROM videos GROUP BY 1 ORDER BY 2 DESC;" 2>/dev/null || echo "(fara tabela videos)"
echo "=== video_assets pe status ==="
$PSQL "SELECT COALESCE(status,'?'), count(*) FROM video_assets GROUP BY 1;" 2>/dev/null || echo "(fara)"
echo "=== produse active ==="
$PSQL "SELECT count(*) FROM marketplace_products;" 2>/dev/null || echo "(fara marketplace_products)"
$PSQL "SELECT status, count(*) FROM marketplace_products GROUP BY 1;" 2>/dev/null
echo "=== useri ==="
$PSQL "SELECT count(*) FROM users;" 2>/dev/null || $PSQL "SELECT count(*) FROM social_users;" 2>/dev/null
echo "=== comenzi ==="
$PSQL "SELECT COALESCE(status,'?'), count(*) FROM commerce_orders GROUP BY 1 ORDER BY 2 DESC;"
echo "=== curse go ==="
$PSQL "SELECT COALESCE(status,'?'), count(*) FROM rides GROUP BY 1 ORDER BY 2 DESC;" 2>/dev/null || echo "(fara tabela rides)"
echo "=== comenzi eats ==="
$PSQL "SELECT COALESCE(status,'?'), count(*) FROM local_orders GROUP BY 1 ORDER BY 2 DESC;"
echo "=== restaurante/merchants ==="
$PSQL "SELECT count(*) FROM local_merchants;" 2>/dev/null || echo "(fara local_merchants)"
echo "=== drivers ==="
$PSQL "SELECT COALESCE(status,'?'), count(*) FROM drivers GROUP BY 1;" 2>/dev/null || echo "(fara drivers)"
echo "=== swyp ledger ==="
$PSQL "SELECT kind, count(*), SUM(amount_units) FROM swyp_ledger_entries GROUP BY 1 ORDER BY 2 DESC LIMIT 8;"
echo "=== mining sessions ==="
$PSQL "SELECT count(*) FROM swyp_mining_sessions;"
echo "=== stays ==="
$PSQL "SELECT count(*) FROM stay_properties;" 2>/dev/null || echo "(fara stay_properties)"
