import fs from "node:fs";
const K = {
    ro: { fromLabel: "De la", toLabel: "Spre", toPlaceholder: "ex: Barcelona", departure: "Plecare", passengers: "Pasageri", ticketIssued: "Bilet emis! ✈️", bookingRef: "Cod rezervare (PNR)", fromPrice: "de la {price}", filterAll: "Toate ({count})", filterDirect: "Doar directe", filterCheap: "Top ieftine", filterFast: "Top rapide", instantIssue: "emitere instant ⚡", viaKiwi: "via Kiwi", firstName: "Prenume", lastName: "Nume", contactEmail: "Email contact", phone: "Telefon" },
    en: { fromLabel: "From", toLabel: "To", toPlaceholder: "e.g. Barcelona", departure: "Departure", passengers: "Passengers", ticketIssued: "Ticket issued! ✈️", bookingRef: "Booking reference (PNR)", fromPrice: "from {price}", filterAll: "All ({count})", filterDirect: "Direct only", filterCheap: "Cheapest", filterFast: "Fastest", instantIssue: "instant ticketing ⚡", viaKiwi: "via Kiwi", firstName: "First name", lastName: "Last name", contactEmail: "Contact email", phone: "Phone" },
    es: { fromLabel: "Desde", toLabel: "Hacia", toPlaceholder: "ej.: Barcelona", departure: "Salida", passengers: "Pasajeros", ticketIssued: "¡Billete emitido! ✈️", bookingRef: "Código de reserva (PNR)", fromPrice: "desde {price}", filterAll: "Todos ({count})", filterDirect: "Solo directos", filterCheap: "Más baratos", filterFast: "Más rápidos", instantIssue: "emisión instantánea ⚡", viaKiwi: "vía Kiwi", firstName: "Nombre", lastName: "Apellidos", contactEmail: "Email de contacto", phone: "Teléfono" },
    fr: { fromLabel: "De", toLabel: "Vers", toPlaceholder: "ex : Barcelone", departure: "Départ", passengers: "Passagers", ticketIssued: "Billet émis ! ✈️", bookingRef: "Référence de réservation (PNR)", fromPrice: "dès {price}", filterAll: "Tous ({count})", filterDirect: "Directs uniquement", filterCheap: "Les moins chers", filterFast: "Les plus rapides", instantIssue: "émission instantanée ⚡", viaKiwi: "via Kiwi", firstName: "Prénom", lastName: "Nom", contactEmail: "Email de contact", phone: "Téléphone" },
    de: { fromLabel: "Von", toLabel: "Nach", toPlaceholder: "z. B. Barcelona", departure: "Abflug", passengers: "Passagiere", ticketIssued: "Ticket ausgestellt! ✈️", bookingRef: "Buchungscode (PNR)", fromPrice: "ab {price}", filterAll: "Alle ({count})", filterDirect: "Nur Direktflüge", filterCheap: "Günstigste", filterFast: "Schnellste", instantIssue: "Sofortausstellung ⚡", viaKiwi: "über Kiwi", firstName: "Vorname", lastName: "Nachname", contactEmail: "Kontakt-E-Mail", phone: "Telefon" },
    pt: { fromLabel: "De", toLabel: "Para", toPlaceholder: "ex.: Barcelona", departure: "Partida", passengers: "Passageiros", ticketIssued: "Bilhete emitido! ✈️", bookingRef: "Código de reserva (PNR)", fromPrice: "desde {price}", filterAll: "Todos ({count})", filterDirect: "Só diretos", filterCheap: "Mais baratos", filterFast: "Mais rápidos", instantIssue: "emissão instantânea ⚡", viaKiwi: "via Kiwi", firstName: "Nome", lastName: "Apelido", contactEmail: "Email de contacto", phone: "Telefone" },
    it: { fromLabel: "Da", toLabel: "Verso", toPlaceholder: "es.: Barcellona", departure: "Partenza", passengers: "Passeggeri", ticketIssued: "Biglietto emesso! ✈️", bookingRef: "Codice prenotazione (PNR)", fromPrice: "da {price}", filterAll: "Tutti ({count})", filterDirect: "Solo diretti", filterCheap: "Più economici", filterFast: "Più veloci", instantIssue: "emissione istantanea ⚡", viaKiwi: "via Kiwi", firstName: "Nome", lastName: "Cognome", contactEmail: "Email di contatto", phone: "Telefono" },
};
for (const [lang, keys] of Object.entries(K)) {
    const p = `messages/${lang}.json`;
    const m = JSON.parse(fs.readFileSync(p, "utf8"));
    m.flyPage = { ...m.flyPage, ...keys };
    fs.writeFileSync(p, JSON.stringify(m, null, 2) + "\n");
    console.log(lang, "+", Object.keys(keys).length);
}
