import fs from "node:fs";

// 1) namespace flyPage × 7 limbi
const K = {
    ro: { searchFailed: "Căutarea a eșuat", offerExpired: "Oferta a expirat. Reia căutarea.", priceUp: "Prețul a crescut cu {delta} — noul total: {total}. Apasă din nou pentru a confirma.", priceDown: "Veste bună: prețul a scăzut! Noul total: {total}. Apasă din nou pentru a confirma.", priceChanged: "Prețul s-a schimbat: noul total e {total}. Apasă din nou pentru a confirma.", authRequired: "Autentifică-te pentru a rezerva (contul tău Swypik).", bookingFailed: "Rezervarea a eșuat", finalPriceNote: "Prețul afișat e prețul final. În lei, fără taxe ascunse.", fromPlaceholder: "ex: București", returnOptional: "Întoarcere (opțional)", adult: "adult", adults: "adulți", search: "Caută", detailsSent: "Detaliile au fost trimise pe email. Poftă bună în drum spre aeroport! ✈️", popularFrom: "Destinații populare din {city}", livePrices: "prețuri live, actualizate zilnic", tapDestination: "Atinge o destinație și vezi toate zborurile — prețul final, fără taxe ascunse.", flightsFound: "{count} zboruri găsite · totalul include toate taxele", noFlights: "Nu am găsit zboruri pentru datele alese. Încearcă alte date.", direct: "direct", stops: "{count} escală", passengersPayment: "Pasageri & plată", backToResults: "înapoi la rezultate", passengerN: "Pasager {n} (ca în pașaport)", birthDate: "Data nașterii", totalToPay: "Total de plată", priceRecheck: "Prețul e reverificat live la furnizor înainte de plată. Emitere instant pentru ofertele Duffel." },
    en: { searchFailed: "Search failed", offerExpired: "The offer expired. Search again.", priceUp: "The price went up by {delta} — new total: {total}. Tap again to confirm.", priceDown: "Good news: the price dropped! New total: {total}. Tap again to confirm.", priceChanged: "The price changed: the new total is {total}. Tap again to confirm.", authRequired: "Sign in to book (your Swypik account).", bookingFailed: "Booking failed", finalPriceNote: "The price shown is the final price. In lei, no hidden fees.", fromPlaceholder: "e.g. London", returnOptional: "Return (optional)", adult: "adult", adults: "adults", search: "Search", detailsSent: "Details were sent by email. Safe travels to the airport! ✈️", popularFrom: "Popular destinations from {city}", livePrices: "live prices, updated daily", tapDestination: "Tap a destination to see all flights — final price, no hidden fees.", flightsFound: "{count} flights found · total includes all taxes", noFlights: "No flights found for the chosen dates. Try different dates.", direct: "direct", stops: "{count} stop", passengersPayment: "Passengers & payment", backToResults: "back to results", passengerN: "Passenger {n} (as in passport)", birthDate: "Date of birth", totalToPay: "Total to pay", priceRecheck: "The price is re-checked live with the provider before payment. Instant ticketing for Duffel offers." },
    es: { searchFailed: "La búsqueda falló", offerExpired: "La oferta caducó. Vuelve a buscar.", priceUp: "El precio subió {delta} — nuevo total: {total}. Pulsa de nuevo para confirmar.", priceDown: "¡Buenas noticias: el precio bajó! Nuevo total: {total}. Pulsa de nuevo para confirmar.", priceChanged: "El precio cambió: el nuevo total es {total}. Pulsa de nuevo para confirmar.", authRequired: "Inicia sesión para reservar (tu cuenta Swypik).", bookingFailed: "La reserva falló", finalPriceNote: "El precio mostrado es el precio final. En lei, sin cargos ocultos.", fromPlaceholder: "ej.: Madrid", returnOptional: "Vuelta (opcional)", adult: "adulto", adults: "adultos", search: "Buscar", detailsSent: "Los detalles se enviaron por email. ¡Buen viaje al aeropuerto! ✈️", popularFrom: "Destinos populares desde {city}", livePrices: "precios en vivo, actualizados a diario", tapDestination: "Toca un destino y ve todos los vuelos — precio final, sin cargos ocultos.", flightsFound: "{count} vuelos encontrados · el total incluye todas las tasas", noFlights: "No encontramos vuelos para esas fechas. Prueba otras fechas.", direct: "directo", stops: "{count} escala", passengersPayment: "Pasajeros y pago", backToResults: "volver a los resultados", passengerN: "Pasajero {n} (como en el pasaporte)", birthDate: "Fecha de nacimiento", totalToPay: "Total a pagar", priceRecheck: "El precio se verifica en vivo con el proveedor antes del pago. Emisión instantánea para ofertas Duffel." },
    fr: { searchFailed: "La recherche a échoué", offerExpired: "L'offre a expiré. Relancez la recherche.", priceUp: "Le prix a augmenté de {delta} — nouveau total : {total}. Appuyez à nouveau pour confirmer.", priceDown: "Bonne nouvelle : le prix a baissé ! Nouveau total : {total}. Appuyez à nouveau pour confirmer.", priceChanged: "Le prix a changé : le nouveau total est {total}. Appuyez à nouveau pour confirmer.", authRequired: "Connectez-vous pour réserver (votre compte Swypik).", bookingFailed: "La réservation a échoué", finalPriceNote: "Le prix affiché est le prix final. En lei, sans frais cachés.", fromPlaceholder: "ex. : Paris", returnOptional: "Retour (facultatif)", adult: "adulte", adults: "adultes", search: "Rechercher", detailsSent: "Les détails ont été envoyés par email. Bon voyage vers l'aéroport ! ✈️", popularFrom: "Destinations populaires depuis {city}", livePrices: "prix en direct, mis à jour quotidiennement", tapDestination: "Touchez une destination pour voir tous les vols — prix final, sans frais cachés.", flightsFound: "{count} vols trouvés · le total inclut toutes les taxes", noFlights: "Aucun vol trouvé pour ces dates. Essayez d'autres dates.", direct: "direct", stops: "{count} escale", passengersPayment: "Passagers et paiement", backToResults: "retour aux résultats", passengerN: "Passager {n} (comme sur le passeport)", birthDate: "Date de naissance", totalToPay: "Total à payer", priceRecheck: "Le prix est revérifié en direct auprès du fournisseur avant le paiement. Émission instantanée pour les offres Duffel." },
    de: { searchFailed: "Suche fehlgeschlagen", offerExpired: "Das Angebot ist abgelaufen. Suche erneut.", priceUp: "Der Preis ist um {delta} gestiegen — neuer Gesamtpreis: {total}. Tippe erneut zum Bestätigen.", priceDown: "Gute Nachricht: Der Preis ist gefallen! Neuer Gesamtpreis: {total}. Tippe erneut zum Bestätigen.", priceChanged: "Der Preis hat sich geändert: Der neue Gesamtpreis ist {total}. Tippe erneut zum Bestätigen.", authRequired: "Melde dich an, um zu buchen (dein Swypik-Konto).", bookingFailed: "Buchung fehlgeschlagen", finalPriceNote: "Der angezeigte Preis ist der Endpreis. In Lei, ohne versteckte Gebühren.", fromPlaceholder: "z. B. Berlin", returnOptional: "Rückflug (optional)", adult: "Erwachsener", adults: "Erwachsene", search: "Suchen", detailsSent: "Die Details wurden per E-Mail gesendet. Gute Reise zum Flughafen! ✈️", popularFrom: "Beliebte Ziele ab {city}", livePrices: "Live-Preise, täglich aktualisiert", tapDestination: "Tippe auf ein Ziel und sieh alle Flüge — Endpreis, ohne versteckte Gebühren.", flightsFound: "{count} Flüge gefunden · Gesamtpreis inkl. aller Steuern", noFlights: "Keine Flüge für die gewählten Daten gefunden. Versuche andere Daten.", direct: "direkt", stops: "{count} Zwischenstopp", passengersPayment: "Passagiere & Zahlung", backToResults: "zurück zu den Ergebnissen", passengerN: "Passagier {n} (wie im Reisepass)", birthDate: "Geburtsdatum", totalToPay: "Zu zahlender Gesamtbetrag", priceRecheck: "Der Preis wird vor der Zahlung live beim Anbieter geprüft. Sofortige Ausstellung bei Duffel-Angeboten." },
    pt: { searchFailed: "A pesquisa falhou", offerExpired: "A oferta expirou. Pesquise novamente.", priceUp: "O preço subiu {delta} — novo total: {total}. Toque novamente para confirmar.", priceDown: "Boa notícia: o preço baixou! Novo total: {total}. Toque novamente para confirmar.", priceChanged: "O preço mudou: o novo total é {total}. Toque novamente para confirmar.", authRequired: "Inicie sessão para reservar (a sua conta Swypik).", bookingFailed: "A reserva falhou", finalPriceNote: "O preço apresentado é o preço final. Em lei, sem taxas escondidas.", fromPlaceholder: "ex.: Lisboa", returnOptional: "Regresso (opcional)", adult: "adulto", adults: "adultos", search: "Pesquisar", detailsSent: "Os detalhes foram enviados por email. Boa viagem até ao aeroporto! ✈️", popularFrom: "Destinos populares a partir de {city}", livePrices: "preços ao vivo, atualizados diariamente", tapDestination: "Toque num destino e veja todos os voos — preço final, sem taxas escondidas.", flightsFound: "{count} voos encontrados · o total inclui todas as taxas", noFlights: "Não encontrámos voos para essas datas. Tente outras datas.", direct: "direto", stops: "{count} escala", passengersPayment: "Passageiros e pagamento", backToResults: "voltar aos resultados", passengerN: "Passageiro {n} (como no passaporte)", birthDate: "Data de nascimento", totalToPay: "Total a pagar", priceRecheck: "O preço é verificado ao vivo junto do fornecedor antes do pagamento. Emissão instantânea para ofertas Duffel." },
    it: { searchFailed: "La ricerca non è riuscita", offerExpired: "L'offerta è scaduta. Ripeti la ricerca.", priceUp: "Il prezzo è salito di {delta} — nuovo totale: {total}. Tocca di nuovo per confermare.", priceDown: "Buone notizie: il prezzo è sceso! Nuovo totale: {total}. Tocca di nuovo per confermare.", priceChanged: "Il prezzo è cambiato: il nuovo totale è {total}. Tocca di nuovo per confermare.", authRequired: "Accedi per prenotare (il tuo account Swypik).", bookingFailed: "La prenotazione non è riuscita", finalPriceNote: "Il prezzo mostrato è quello finale. In lei, senza costi nascosti.", fromPlaceholder: "es.: Roma", returnOptional: "Ritorno (facoltativo)", adult: "adulto", adults: "adulti", search: "Cerca", detailsSent: "I dettagli sono stati inviati via email. Buon viaggio verso l'aeroporto! ✈️", popularFrom: "Destinazioni popolari da {city}", livePrices: "prezzi live, aggiornati ogni giorno", tapDestination: "Tocca una destinazione e vedi tutti i voli — prezzo finale, senza costi nascosti.", flightsFound: "{count} voli trovati · il totale include tutte le tasse", noFlights: "Nessun volo trovato per le date scelte. Prova altre date.", direct: "diretto", stops: "{count} scalo", passengersPayment: "Passeggeri e pagamento", backToResults: "torna ai risultati", passengerN: "Passeggero {n} (come sul passaporto)", birthDate: "Data di nascita", totalToPay: "Totale da pagare", priceRecheck: "Il prezzo viene ricontrollato live presso il fornitore prima del pagamento. Emissione istantanea per le offerte Duffel." },
};
for (const [l, keys] of Object.entries(K)) {
    const file = `messages/${l}.json`;
    const j = JSON.parse(fs.readFileSync(file, "utf8"));
    j.flyPage = { ...(j.flyPage || {}), ...keys };
    fs.writeFileSync(file, JSON.stringify(j, null, 2) + "\n");
}
console.log("flyPage +" + Object.keys(K.ro).length + " chei × 7");

// 2) component
const f = "app/[locale]/fly/FlyClient.tsx";
let c = fs.readFileSync(f, "utf8");
const R = [
    ['json.error ?? "Căutarea a eșuat"', 'json.error ?? t("searchFailed")'],
    ['pcJson.message ?? "Oferta a expirat. Reia căutarea."', 'pcJson.message ?? t("offerExpired")'],
    ["`Prețul a crescut cu ${eur(pcJson.deltaCents)} — noul total: ${eur(pcJson.totalCents)}. Apasă din nou pentru a confirma.`", 't("priceUp", { delta: eur(pcJson.deltaCents), total: eur(pcJson.totalCents) })'],
    ["`Veste bună: prețul a scăzut! Noul total: ${eur(pcJson.totalCents)}. Apasă din nou pentru a confirma.`", 't("priceDown", { total: eur(pcJson.totalCents) })'],
    ["`Prețul s-a schimbat: noul total e ${eur(json.newTotalCents)}. Apasă din nou pentru a confirma.`", 't("priceChanged", { total: eur(json.newTotalCents) })'],
    ['"Autentifică-te pentru a rezerva (contul tău Swypik)."', 't("authRequired")'],
    ['json.error ?? "Rezervarea a eșuat"', 'json.error ?? t("bookingFailed")'],
    ["Prețul afișat e prețul final. În lei, fără taxe ascunse.", '{t("finalPriceNote")}'],
    ['placeholder="ex: București"', 'placeholder={t("fromPlaceholder")}'],
    ["<CalendarDays size={12} /> Întoarcere (opțional)", '<CalendarDays size={12} /> {t("returnOptional")}'],
    ['{n} {n === 1 ? "adult" : "adulți"}', '{n} {n === 1 ? t("adult") : t("adults")}'],
    [">\n                            Caută", '>\n                            {t("search")}'],
    ["Detaliile au fost trimise pe email. Poftă bună în drum spre aeroport! ✈️", '{t("detailsSent")}'],
    ["Destinații populare din București", '{t("popularFrom", { city: "București" })}'],
    ["prețuri live, actualizate zilnic", '{t("livePrices")}'],
    ["Atinge o destinație și vezi toate zborurile — prețul final, fără taxe ascunse.", '{t("tapDestination")}'],
    ["{offers.length} zboruri găsite · totalul include t", '{t("flightsFound", { count: offers.length })}{"" /* legacy: t'],
    ['{s.segments.length - 1 === 0 ? "direct" : `${s.segments.length - 1} escală`}', '{s.segments.length - 1 === 0 ? t("direct") : t("stops", { count: s.segments.length - 1 })}'],
    ["<h2 className=\"font-bold\">Pasageri & plată</h2>", '<h2 className="font-bold">{t("passengersPayment")}</h2>'],
    [">înapoi la rezultate<", ">{t(\"backToResults\")}<"],
    ["Pasager {i + 1} (ca în pașa", '{t("passengerN", { n: i + 1 })}{"" /* legacy: '],
    [">Data nașterii<", ">{t(\"birthDate\")}<"],
    [">Total de plată<", ">{t(\"totalToPay\")}<"],
    ["Prețul e reverificat live la furnizor înainte de plată. Emitere instant pentru ofertele Du", '{t("priceRecheck")}{"" /* legacy: '],
];
let miss = [];
for (const [a, b] of R) {
    if (c.includes(a)) c = c.replaceAll(a, b);
    else miss.push(a.slice(0, 50));
}
if (!c.includes("useTranslations")) {
    c = c.replace(/(import[^\n]*from "next\/navigation";)/, '$1\nimport { useTranslations } from "next-intl";');
    // adaugă hook-ul în componentă (prima linie după declarația funcției principale)
    c = c.replace(/(export default function \w+\([^)]*\)\s*\{)/, '$1\n    const t = useTranslations("flyPage");');
}
fs.writeFileSync(f, c);
console.log(miss.length ? "NEGĂSITE:\n" + miss.join("\n") : "toate înlocuite");
