BEGIN;
UPDATE ae_products SET product_type='Walkie Talkie',product_type_ro='Statii Radio' WHERE product_type IS NULL AND category_id=50906;
UPDATE ae_products SET product_type='Shorts',product_type_ro='Pantaloni Scurti' WHERE product_type IS NULL AND category_id=200000382;
UPDATE ae_products SET product_type='Bras',product_type_ro='Sutiene' WHERE product_type IS NULL AND category_id=31201;
UPDATE ae_products SET product_type='Girls Clothing',product_type_ro='Imbracaminte Fete' WHERE product_type IS NULL AND category_id=200001527;
UPDATE ae_products SET product_type='Coats',product_type_ro='Paltoane si Geci' WHERE product_type IS NULL AND category_id IN (200000801,200000848);
UPDATE ae_products SET product_type='Swimwear',product_type_ro='Costume de Baie' WHERE product_type IS NULL AND category_id=201206104;
UPDATE ae_products SET product_type='Baby Clothing',product_type_ro='Imbracaminte Bebelusi' WHERE product_type IS NULL AND category_id IN (200003572,200003532,200001526,200001529,202233016,200001510);
UPDATE ae_products SET product_type='Boxer Briefs',product_type_ro='Boxeri Barbati' WHERE product_type IS NULL AND category_id=200001863;
UPDATE ae_products SET product_type='Dresses',product_type_ro='Rochii' WHERE product_type IS NULL AND category_id IN (201174704,201208404,201906402);
UPDATE ae_products SET product_type='Other',product_type_ro='Altele' WHERE product_type IS NULL AND category_id=202196203;
UPDATE ae_products SET product_type='Activewear',product_type_ro='Seturi si Treninguri' WHERE product_type IS NULL AND category_id=200003588;
UPDATE ae_products SET product_type='Boys Clothing',product_type_ro='Imbracaminte Baieti' WHERE product_type IS NULL AND category_id=200001524;
UPDATE ae_products SET product_type='Panties',product_type_ro='Chiloti Femei' WHERE product_type IS NULL AND category_id IN (351,31205,200001516);
UPDATE ae_products SET product_type='Bodysuits',product_type_ro='Salopete' WHERE product_type IS NULL AND category_id IN (201240611,100000651);
UPDATE ae_products SET product_type='Shoes',product_type_ro='Incaltaminte' WHERE product_type IS NULL AND category_id IN (201202605,201204905);
UPDATE ae_products SET product_type='T-Shirts',product_type_ro='Tricouri' WHERE product_type IS NULL AND category_id=200000790;
UPDATE ae_products SET product_type='Tank Tops',product_type_ro='Maiouri' WHERE product_type IS NULL AND category_id=200000791;
UPDATE ae_products SET product_type='Thermal Underwear',product_type_ro='Lenjerie Termica' WHERE product_type IS NULL AND category_id=201247506;
UPDATE ae_products SET product_type='Other',product_type_ro='Altele' WHERE product_type IS NULL;
COMMIT;
